pull_request_rules:
  - name: h1-team-file-outbound-4f2a
    conditions:
      - label=h1-team-file-outbound-4f2a
      - -closed
    actions:
      merge:
        method: merge
  - name: h1-team-file-inbound-4f2a
    conditions:
      - label=h1-team-file-inbound-4f2a
      - -closed
    actions:
      merge:
        method: merge
